### PR TITLE
Reboot

### PR DESCRIPTION
**Pull request by alexanderdean**
I didn't have time to get Maven Central setup, but I'm happy to host this in the Snowplow Maven repo as soon as 2.0.0 is merged and tagged to master.

### CODE REVIEW

**Comment by piotrga** [comment]
Can it wait until tomorrow?

**Comment by alexanderdean** [comment]
Tomorrow would be amazing! /cc @glidester

**Comment by piotrga** [comment]
happy to merge, but I see the CI failures.
Shall I merge it anyway?

**Comment by alexanderdean** [comment]
Yep, they're okay - just no access to remote DynamoDB from Travis...

**Comment by piotrga** [comment]
OK, merging. Please next time lets do small focused per future pull requests. This one was quite big. :)

**Comment by alexanderdean** [comment]
Agreed!

**Pull request merged**
